---
version: "2.4"

networks:
  elastic: {}

volumes:
  elasticsearch-data: {}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - elastic
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -f localhost:9200
      interval: 12s
      timeout: 5s
      retries: 15
      start_period: 15s

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic
    ports:
      - 5601:5601
