{
 "title": "Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rpc_service",
    "label": "RPC Service",
    "query": "label_values(rpc_durations_seconds, service)"
   },
   {
    "name": "rpc_quantile",
    "label": "RPC Quantiles",
    "query": "label_values(rpc_durations_seconds, quantile)"
   }
  ]
 },
 "panels": [
  { "title": "Random ($rpc_service)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "rpc_service" },
  {
   "title": "$rpc_quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "repeat": "rpc_quantile",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rpc_durations_seconds{quantile=~\"$rpc_quantile\", service=\"$rpc_service\"}"
    }
   ]
  },
  {
   "title": "$rpc_quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rpc_durations_seconds{quantile=~\"$rpc_quantile\", service=\"$rpc_service\"}"
    }
   ]
  },
  {
   "title": "$rpc_quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rpc_durations_seconds{quantile=~\"$rpc_quantile\", service=\"$rpc_service\"}"
    }
   ]
  },
  { "title": "Random ($rpc_service)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$rpc_quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "repeat": "rpc_quantile",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rpc_durations_seconds{quantile=~\"$rpc_quantile\", service=\"$rpc_service\"}"
    }
   ]
  },
  {
   "title": "$rpc_quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rpc_durations_seconds{quantile=~\"$rpc_quantile\", service=\"$rpc_service\"}"
    }
   ]
  },
  {
   "title": "$rpc_quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rpc_durations_seconds{quantile=~\"$rpc_quantile\", service=\"$rpc_service\"}"
    }
   ]
  },
  { "title": "Random ($rpc_service)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$rpc_quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "repeat": "rpc_quantile",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rpc_durations_seconds{quantile=~\"$rpc_quantile\", service=\"$rpc_service\"}"
    }
   ]
  },
  {
   "title": "$rpc_quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rpc_durations_seconds{quantile=~\"$rpc_quantile\", service=\"$rpc_service\"}"
    }
   ]
  },
  {
   "title": "$rpc_quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rpc_durations_seconds{quantile=~\"$rpc_quantile\", service=\"$rpc_service\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Ethernet Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=~\"node\",device=\"eth0\"}[30s]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{job=~\"node\",device=\"eth0\"}[30s]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "CPU Load5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes)"
    }
   ]
  }
 ]
}