---
version: '3'

networks:
  matomo:
  cache:
  proxy:

volumes:
  matomo-db-data:
  matomo-data:
  openresty-data:

services:
  matomo-db:
    image: mariadb:10
    networks:
      - matomo
    volumes:
      - matomo-db-data:/var/lib/mysql
    environment:
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=matomo
      - MYSQL_DATABASE=matomo

  matomo:
    image: matomo:3.5-fpm-alpine
    networks:
      - matomo
      - proxy
    volumes:
      - matomo-data:/var/www/html/config

  redis:
    image: redis:4-alpine
    networks:
      - cache
    ports:
      - 6379:6379

  openresty:
    image: openresty:stretch
    networks:
      - cache
      - proxy
    ports:
      - 80:80
