---
version: '3'

networks:
  ripley:
  thor:

volumes:
  grafana-data:
  prometheus-data:

services:
  grafana:
    image: grafana/grafana:6.4.3
    depends_on:
      - loki
      - prometheus
    networks:
      - ripley
      - thor
    ports:
      - 13000:3000
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/all.yml:ro
      - ./grafana/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ./grafana/dashboards:/opt/dashboards
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.13.1
    networks:
      - ripley
    ports:
      - 19090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml:ro
      - prometheus-data:/prometheus

  node-exporter:
    image: prom/node-exporter:v0.18.0
    networks:
      ripley:
    pid: 'host'
    ports:
      - 19100:9100
    cap_add:
      - SYS_TIME
    volumes:
      - "/proc:/host/proc:ro,rslave"
      - "/sys:/host/sys:ro,rslave"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'

  random-one:
    image: local/go-random
    build: ./go-random
    environment:
      LISTEN_PORT: 8081
    networks:
      - ripley

  random-two:
    image: local/go-random
    build: ./go-random
    environment:
      LISTEN_PORT: 8082
    networks:
      - ripley

  random-three:
    image: local/go-random
    build: ./go-random
    environment:
      LISTEN_PORT: 8083
    networks:
      - ripley

  loki:
    image: grafana/loki:v0.4.0
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - thor

  promtail:
    image: grafana/promtail:v0.4.0
    volumes:
      - '/var/log:/var/log:ro,rslave'
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - thor
