---
version: "3"

networks:
  magento-db: {}
  magento-http: {}

volumes:
  db-data: {}
  es-data: {}
  magento-data: {}

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    networks:
      - magento-db
    volumes:
      - db-data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    networks:
      - magento-db
    volumes:
      - es-data:/usr/share/elasticsearch/data

  magento:
    build: ./magento
    depends_on:
      - db
      - elasticsearch
      - redis
    networks:
      - magento-db
      - magento-http
    #ports:
    #  - 9080:80
    volumes:
      - magento-data:/var/www/magento

  redis:
    image: redis:5-buster
    networks:
      - magento-db

  varnish:
    image: varnish:6.3
    depends_on:
      - magento
    networks:
      - magento-http
    ports:
      - 80:80
    tmpfs:
      - /usr/local/var/varnish:exec
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
