global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'go-random'
    scrape_interval: 10s
    static_configs:
      - targets: ['random-one:8081', 'random-two:8082']
        labels:
          group: 'production'
      - targets: ['random-three:8083']
        labels:
          group: 'canary'
