---
apiVersion: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    org_id: 1
    url: 'http://prometheus:9090'
    is_default: true
    version: 1
    editable: true

  - name: 'Jaeger'
    type: 'jaeger'
    access: 'proxy'
    url: 'http://jaeger-query:16686'

  - name: 'Loki'
    type: 'loki'
    access: 'proxy'
    url: 'http://loki:3100'
    jsonData:
      maxLines: 1000
