---
version: "3"

networks:
  jaeger: {}

volumes:
  cassandra-data: {}

services:
  cassandra:
    image: cassandra:3.9
    networks:
      jaeger: {}
    volumes:
      - cassandra-data:/var/lib/cassandra

  hotrod:
    image: jaegertracing/example-hotrod:1.16
    command: "all"
    environment:
      JAEGER_AGENT_HOST: jaeger-agent
    networks:
      jaeger: {}
    ports:
      - 8080:8080

  jaeger-cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.16
    depends_on:
      - cassandra
    networks:
      jaeger: {}

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.16
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    depends_on:
      - jaeger-collector
    networks:
      jaeger: {}

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.16
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
    depends_on:
      - jaeger-cassandra-schema
    networks:
      jaeger: {}

  jaeger-query:
    image: jaegertracing/jaeger-query:1.16
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
    networks:
      jaeger: {}
    ports:
      - 16686:16686

  jaeger-spark-dependencies:
    image: jaegertracing/spark-dependencies:latest
    depends_on:
      - cassandra
    environment:
      STORAGE: cassandra
      CASSANDRA_CONTACT_POINTS: cassandra
    networks:
      jaeger: {}
