version: '3'

networks:
  quickwit: {}

volumes:
  minio-data: {}
  postgres-data: {}
  quickwit-data: {}

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    networks:
      quickwit:
        aliases:
          - minio.local
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -I http://localhost:9000/minio/health/live"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 9000:9000 # HTTP API
      - 9090:9090 # Web Console
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: quickwit-admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: quickwit
      POSTGRES_USER: quickwit
      POSTGRES_PASSWORD: dbpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d quickwit" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - quickwit
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  quickwit:
    image: quickwit/quickwit:0.6.1
    command: run
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - quickwit
    ports:
      - 7280:7280
    volumes:
      - quickwit-data:/quickwit/qwdata
      - ./quickwit:/etc/quickwit:ro
    environment:
      AWS_REGION: local
      AWS_ACCESS_KEY_ID: ${MINIO_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${MINIO_AWS_SECRET_ACCESS_KEY}
      QW_CONFIG: /etc/quickwit/quickwit.yaml
